### PR TITLE
Resolve issue 80 - MIME extensions for non-JSON providers

### PR DESCRIPTION
**Pull request by kleinsch**

### CODE REVIEW

**Comment by cowtowncoder** [comment]
I think this requires discussion on dev mailing list: wouldn't this change break any content type negotiation, and make it impossible to match by content type for the common case of using standard mime types? Or would the limitation to only supported type be handled in methods, and annotation would basically be ignored (as they pass everything)?

I understand the challenge of supporting structured mime types, so I am not saying no change is needed; I just want to understand what implications there would be.

**Comment by kleinsch** [comment]
Yes, it's the latter - the annotations are ignored and delegate to the methods. This logic has already been released in the JSON provider, I just copied it over to the other providers.

**Comment by kleinsch** [comment]
@cowtowncoder Good call. Added a test that registers YAML, Json, and Smile providers and makes sense each is used for its MIME types.

**Comment by cowtowncoder** [comment]
Great. Ok, one thing I do need before merging (I'll also re-read the patch but aside) is CLA:

https://github.com/FasterXML/jackson/blob/master/contributor-agreement.pdf

which us just needed before the first contribution. The easiest way is to print it, fill & sign, scan and email to `info` at fasterxml dot com. If you could do that, it'd be great -- we need to get this done just once and further contributions for all Jackson components can be under this one CLA.

Thank you for the contribution!

**Comment by kleinsch** [comment]
Done. Should be in your email now.

**Comment by cowtowncoder** [comment]
Thanks!

**Pull request merged**
