### PR TITLE
Increase jax rs spec version range, fix for #97

### PR DESCRIPTION
**Pull request by cschneider**

### CODE REVIEW

**Comment by cowtowncoder** [comment]
Is this known to be safe? Are there newer versions of the API jar?

**Comment by cschneider** [comment]
I documented the API bundle we use in the issue. As far as I know it should be safe for jackson. I corrected my comment on the issue. jaxrs 2.1 is not in CXF 3.1.10 but only in the upcoming CXF 3.2.0.

**Comment by cowtowncoder** [comment]
Build is failing for some reason, I don't think it is related to this change (`master` is failing at this point).
Need to see what gives.

**Comment by pavelbucek** [comment]
@cowtowncoder Hi Tatu,

could we get this resolved as soon as possible, ideally followed by a prompt Jackson release?

The change looks fine - I do have this tested with range changed to [2.0, 3.0) and it works on GF.

    $ cat ./...../META-INF/MANIFEST.MF 
    Manifest-Version: 1.0
    Bnd-LastModified: 1476420257898
    Build-Jdk: 1.7.0_79
    Built-By: tatu
    Bundle-Description: Pile of code that is shared by all Jackson-based JAX
     -RSproviders.
    Bundle-DocURL: http://github.com/FasterXML/jackson-jaxrs-providers/jacks
     on-jaxrs-base
    Bundle-License: http://www.apache.org/licenses/LICENSE-2.0.txt
    Bundle-ManifestVersion: 2
    Bundle-Name: Jackson-JAXRS-base
    Bundle-SymbolicName: com.fasterxml.jackson.jaxrs.jackson-jaxrs-base
    Bundle-Vendor: FasterXML
    Bundle-Version: 2.8.4
    Created-By: Apache Maven Bundle Plugin
    Export-Package: com.fasterxml.jackson.jaxrs.annotation;version="2.8.4",c
     om.fasterxml.jackson.jaxrs.base;version="2.8.4",com.fasterxml.jackson.j
     axrs.cfg;version="2.8.4",com.fasterxml.jackson.jaxrs.util;version="2.8.
     4"
    Implementation-Build-Date: 2016-10-14 04:43:22+0000
    Implementation-Title: Jackson-JAXRS-base
    Implementation-Vendor: FasterXML
    Implementation-Vendor-Id: com.fasterxml.jackson.jaxrs
    Implementation-Version: 2.8.4
    Import-Package: javax.ws.rs.core;version="[2.0,3.0)",javax.ws.rs.ext;ver
     sion="[2.0,3.0)",com.fasterxml.jackson.annotation;version="[2.8,3)",com
     .fasterxml.jackson.core;version="[2.8,3)",com.fasterxml.jackson.databin
     d;version="[2.8,3)",com.fasterxml.jackson.databind.cfg;version="[2.8,3)
     ",com.fasterxml.jackson.databind.introspect;version="[2.8,3)",com.faste
     rxml.jackson.databind.type;version="[2.8,3)",com.fasterxml.jackson.data
    bind.util;version="[2.8,3)",com.fasterxml.jackson.jaxrs.annotation;vers
     ion="[2.8,3)",com.fasterxml.jackson.jaxrs.cfg;version="[2.8,3)",com.fas
     terxml.jackson.jaxrs.util;version="[2.8,3)",javax.ws.rs;version="[2.0,3
     .0)"
    Require-Capability: osgi.ee;filter:="(&(osgi.ee=JavaSE)(version=1.7))"
    Specification-Title: Jackson-JAXRS-base
    Specification-Vendor: FasterXML
    Specification-Version: 2.8.4
    Tool: Bnd-3.0.0.201509101326
    X-Compile-Source-JDK: 1.7
    X-Compile-Target-JDK: 1.7

Please note that if this won't be resolved soon, we might be forced to repackage Jackson or replace it by JSON-B. Obviously, we don't want to do any of those, so if this could be fixed on Jackson side, it would save us from working on "meaningless" task.

Thanks and regards,
Pavel Bucek

(current JAX-RS spec lead)

**Comment by cowtowncoder** [comment]
@pavelbucek thanks for ping -- I'm on vacation but back in couple of days, and will work on this as the first thing.

**Comment by pavelbucek** [comment]
@cowtowncoder Thanks for reacting :)

Do you think this could be done today? (our deadline is approaching rapidly and if I won't get your confirmation, I'll have to repackage jackson.jaxrs modules and distribute them as part of Jersey).

**Comment by cowtowncoder** [comment]
@pavelbucek Done.

**Comment by pavelbucek** [comment]
@cowtowncoder perfect, thanks :)

**Comment by pavelbucek** [comment]
@cowtowncoder when could we expect 2.8.10 on maven central?

**Comment by cowtowncoder** [comment]
@pavelbucek I don't know. Cutting a release is quite a bit of work, and right now I am focusing on finalizing 2.9.9, so likely 2.8.10 would be release right after 2.9.0, which would mean towards end of July if all goes well (enough).

**Comment by pavelbucek** [comment]
@cowtowncoder ok, then I need to repackage jackson.jaxrs.

Thanks anyway!

**Pull request merged**
